import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.103.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const DOC_TEMPLATES: Record<string, { title: string; systemAddition: string; userPrompt: string }> = {
  statement_of_work: {
    title: 'Statement of Work',
    systemAddition: 'You are generating a formal Statement of Work document. This will be used in a commercial agreement between Penguin AI and the customer. Be precise, professional, and unambiguous. Every scope item must be traceable to a stated customer need.',
    userPrompt: `Generate a complete Statement of Work for this engagement using the project insights and documents provided.

Additional instructions from the team: [USER_INSTRUCTIONS]

Structure the SOW with these exact sections:

# Statement of Work
## [Customer Name] × Penguin AI

### 1. Executive Summary
### 2. Background and Problem Statement
### 3. Objectives
### 4. Scope of Work
#### 4.1 In Scope
#### 4.2 Out of Scope
#### 4.3 Assumptions
### 5. Solution Overview
### 6. Deliverables
| Deliverable | Description | Phase | Acceptance Criteria |
### 7. Implementation Phases
### 8. Roles and Responsibilities
| Role | Penguin AI | Customer |
### 9. Timeline
### 10. Pricing and Payment (Placeholder)
### 11. Terms and Conditions (Placeholder)
### 12. Sign-off

---
*Generated by ArchBridge AI on [DATE]*
*Sources: [list all document names used]*
*Review and verify all claims against source documents before sending.*`,
  },
  business_requirements: {
    title: 'Business Requirements Document',
    systemAddition: 'You are generating a Business Requirements Document (BRD). Be thorough and traceable. Every requirement must link to a source.',
    userPrompt: `Generate a Business Requirements Document (BRD) for this engagement.

Additional instructions: [USER_INSTRUCTIONS]

# Business Requirements Document
## [Customer Name] — Healthcare AI Automation Initiative

### 1. Introduction
#### 1.1 Purpose
#### 1.2 Scope
#### 1.3 Definitions and Acronyms
### 2. Business Context
#### 2.1 Current State Overview
#### 2.2 Problem Statement
#### 2.3 Business Drivers
### 3. Stakeholders
| Stakeholder | Role | Interest | Influence |
### 4. Business Requirements
**BR-[N]: [Requirement Title]**
- Description:
- Priority: Must Have / Should Have / Nice to Have
- Source: [document name]
- Acceptance Criteria:
- Related Pain Points:
### 5. Functional Requirements Summary
### 6. Non-Functional Requirements
### 7. Constraints and Dependencies
### 8. Risks and Mitigations
### 9. Success Metrics
### 10. Open Questions

---
*Generated by ArchBridge AI · Sources: [document list]*`,
  },
  solution_architecture_doc: {
    title: 'Solution Architecture Document',
    systemAddition: 'You are generating a Solution Architecture Document. Be technically precise while remaining accessible.',
    userPrompt: `Generate a Solution Architecture Document for this engagement.

Additional instructions: [USER_INSTRUCTIONS]

# Solution Architecture Document
## [Customer Name] — Penguin AI Digital Worker Implementation

### 1. Executive Summary
### 2. Solution Overview
### 3. Architecture Principles
### 4. Current State Architecture
### 5. Future State Architecture
#### 5.1 Solution Components
#### 5.2 Integration Architecture
#### 5.3 Data Flow
### 6. Component Specifications
### 7. Security and Compliance
### 8. Infrastructure Requirements
### 9. Integration Specifications
### 10. Implementation Considerations
### 11. Risks and Mitigations
### 12. Architecture Decision Records

---
*Generated by ArchBridge AI · Sources: [document list]*`,
  },
  executive_summary: {
    title: 'Executive Summary',
    systemAddition: 'You are generating a 1-2 page executive summary suitable for C-suite briefing. Be concise and impactful.',
    userPrompt: `Generate a 1-2 page executive summary suitable for a C-suite briefing.

Additional instructions: [USER_INSTRUCTIONS]

# Executive Summary
## [Customer Name] × Penguin AI

[Lead paragraph — bottom line up front]
### The Challenge
### The Opportunity
### Proposed Solution
### Key Benefits
| Benefit | Expected Impact |
### Implementation Approach
### Investment and ROI
### Why Penguin AI
### Recommended Next Steps

---
*Prepared by: [Space for name]*
*Date: [DATE]*`,
  },
  gap_analysis_report: {
    title: 'Gap Analysis Report',
    systemAddition: 'You are generating an internal Gap Analysis Report. Be direct and honest — this is for internal use. Flag real gaps.',
    userPrompt: `Generate a Gap Analysis Report for this engagement. Be direct and honest — this is for internal use.

Additional instructions: [USER_INSTRUCTIONS]

# Gap Analysis Report
## [Customer Name] Engagement — Internal Use Only

### 1. Summary
### 2. Needs vs. Coverage Matrix
| Customer Need | Priority | Penguin AI Coverage | Gap Level | Notes |
### 3. Full Coverage Areas
### 4. Partial Coverage Areas
### 5. Gaps Requiring Custom Build
### 6. Strategic Gaps
### 7. Recommended Approach Per Gap
### 8. Risk Assessment
### 9. Product Team Recommendations

---
*FOR INTERNAL USE ONLY*
*Generated by ArchBridge AI · Sources: [document list]*`,
  },
  implementation_plan: {
    title: 'Implementation Plan',
    systemAddition: 'You are generating a detailed Implementation Plan. Be specific about phases, milestones, and dependencies.',
    userPrompt: `Generate a detailed Implementation Plan document.

Additional instructions: [USER_INSTRUCTIONS]

# Implementation Plan
## [Customer Name] — Penguin AI Engagement

### 1. Overview
### 2. Project Team
| Role | Name (TBD) | Responsibility |
### 3. Phased Implementation Plan
### 4. Milestone Schedule
| Milestone | Phase | Target Date (TBD) | Owner | Success Criteria |
### 5. Dependency Map
### 6. Resource Requirements
### 7. Communication Plan
### 8. Change Management Approach
### 9. Testing and Acceptance Strategy
### 10. Go-Live Plan
### 11. Post Go-Live Support
### 12. Risk Register
| Risk | Probability | Impact | Mitigation | Owner |

---
*Generated by ArchBridge AI · Sources: [document list]*`,
  },
};

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const aiApiKey = Deno.env.get('LOVABLE_API_KEY')!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const userClient = createClient(supabaseUrl, Deno.env.get('SUPABASE_ANON_KEY')!, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user } } = await userClient.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { project_id, template_type, user_instructions } = await req.json();

    if (!project_id || !template_type || !DOC_TEMPLATES[template_type]) {
      return new Response(JSON.stringify({ error: 'project_id and valid template_type required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const template = DOC_TEMPLATES[template_type];

    // Fetch project
    const { data: project } = await supabase.from('projects').select('*').eq('id', project_id).single();
    if (!project) {
      return new Response(JSON.stringify({ error: 'Project not found' }), {
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch documents
    const { data: docs } = await supabase
      .from('documents')
      .select('file_name, file_type, extracted_text, created_at')
      .eq('project_id', project_id)
      .eq('parse_status', 'done')
      .order('created_at', { ascending: false });

    // Fetch insights
    const { data: insights } = await supabase
      .from('project_insights')
      .select('*')
      .eq('project_id', project_id)
      .single();

    // Fetch master prompt
    const { data: configRow } = await supabase
      .from('system_config')
      .select('config_value')
      .eq('config_key', 'master_system_prompt')
      .single();
    const masterPrompt = configRow?.config_value || 'You are ArchBridge AI.';

    // Build document context
    let docContext = '';
    let totalChars = 0;
    const docNames: string[] = [];
    for (const doc of (docs || []).slice(0, 10)) {
      const text = (doc.extracted_text || '').substring(0, 8000);
      if (totalChars + text.length > 80000) break;
      docNames.push(doc.file_name);
      totalChars += text.length;
      docContext += `=== DOCUMENT: ${doc.file_name} (${doc.file_type}) ===\n${text}\n=== END DOCUMENT ===\n\n`;
    }

    // Build insights context
    let insightsContext = '';
    if (insights) {
      insightsContext = `=== PROJECT INSIGHTS (AI-Generated) ===\n${JSON.stringify(insights, null, 2)}\n=== END INSIGHTS ===\n\n`;
    }

    // Fetch previously generated docs of other types
    const { data: prevDocs } = await supabase
      .from('generated_documents')
      .select('document_type, title, content')
      .eq('project_id', project_id)
      .neq('document_type', template_type)
      .neq('document_type', 'critique')
      .order('created_at', { ascending: false })
      .limit(3);

    let prevDocsContext = '';
    if (prevDocs?.length) {
      prevDocsContext = `=== PREVIOUSLY GENERATED DOCUMENTS ===\n`;
      for (const pd of prevDocs) {
        prevDocsContext += `--- ${pd.title} ---\n${(pd.content || '').substring(0, 3000)}\n\n`;
      }
      prevDocsContext += `=== END PREVIOUS DOCS ===\n\n`;
    }

    const systemPrompt = `${masterPrompt}\n\n${template.systemAddition}`;
    const userPrompt = `${docContext}${insightsContext}${prevDocsContext}

Project: ${project.name}
Customer: ${project.customer_name}

${template.userPrompt.replace('[USER_INSTRUCTIONS]', user_instructions || 'None provided').replace('[DATE]', new Date().toISOString().split('T')[0]).replace('[Customer Name]', project.customer_name)}`;

    // Stream from AI
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${aiApiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'google/gemini-3-flash-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        stream: true,
        max_tokens: 8000,
      }),
    });

    if (!aiResponse.ok) {
      if (aiResponse.status === 429) {
        return new Response(JSON.stringify({ error: 'Rate limited.' }), {
          status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      const errText = await aiResponse.text();
      throw new Error(`AI error: ${aiResponse.status} ${errText}`);
    }

    const reader = aiResponse.body!.getReader();
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    let fullContent = '';

    const stream = new ReadableStream({
      async pull(controller) {
        let buffer = '';
        while (true) {
          const { done, value } = await reader.read();
          if (done) {
            // Determine version
            const { data: existingDocs } = await supabase
              .from('generated_documents')
              .select('version')
              .eq('project_id', project_id)
              .eq('document_type', template_type)
              .order('version', { ascending: false })
              .limit(1);
            const nextVersion = ((existingDocs?.[0]?.version as number) || 0) + 1;

            // Save document
            const { data: savedDoc } = await supabase
              .from('generated_documents')
              .insert({
                project_id,
                generated_by: user.id,
                document_type: template_type,
                title: `${template.title} — ${project.customer_name} — v${nextVersion}`,
                content: fullContent,
                sources: docNames.map(n => ({ doc_name: n })),
                version: nextVersion,
              })
              .select()
              .single();

            controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'done', document_id: savedDoc?.id })}\n\n`));
            controller.close();
            return;
          }

          buffer += decoder.decode(value, { stream: true });
          let newlineIdx;
          while ((newlineIdx = buffer.indexOf('\n')) !== -1) {
            let line = buffer.slice(0, newlineIdx);
            buffer = buffer.slice(newlineIdx + 1);
            if (line.endsWith('\r')) line = line.slice(0, -1);
            if (!line.startsWith('data: ')) continue;
            const jsonStr = line.slice(6).trim();
            if (jsonStr === '[DONE]') continue;
            try {
              const parsed = JSON.parse(jsonStr);
              const content = parsed.choices?.[0]?.delta?.content;
              if (content) {
                fullContent += content;
                controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: 'token', content })}\n\n`));
              }
            } catch { /* skip partial */ }
          }
        }
      },
    });

    return new Response(stream, {
      headers: { ...corsHeaders, 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' },
    });

  } catch (err: any) {
    console.error('Generate document error:', err);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
